service: Exomoon-Assets-Renderer

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

package:
  individually: true
  excludeDevDependencies: true

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${env:STAGE}
  environment:
    STAGE: ${self:provider.stage}
    API_GATEWAY_NAME: Exomoon-ApiGateway-Assets-Renderer-${self:provider.stage}

custom:
  stage: ${self:provider.stage}

  serverless-offline:
    httpPort: 3003
    websocketPort: 3004
    lambdaPort: 3005

  webpack:
    packager: yarn
    webpackConfig: "webpack.config.js"
    keepOutputDirectory: true
    includeModules:
      forceExclude:
        - aws-sdk
        - aws-lambda
    excludeFiles: ./**/*.test.js

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:provider.environment.API_GATEWAY_NAME}
        BinaryMediaTypes:
          - "image/png"

  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: exomoon-assets-${self:provider.stage}-ExtApiGatewayRestApiId

    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: exomoon-assets-${self:provider.stage}-ExtApiGatewayRestApiRootResourceId

functions:
  serviceInfo:
    handler: src/functions/serviceInfo.serviceInfo
    events:
      - http:
          cors: true
          method: get
          path: /service-info
